services:
  - type: web
    name: ton-laravel-app
    env: php
    plan: free
    buildCommand: "composer install --no-dev && php artisan key:generate"
    startCommand: "php artisan migrate --force && php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ton-laravel-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ballast.proxy.rlwy.net
      - key: DB_PORT
        value: 52349
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: SkRedTKzFZTPPCdGrmgGWFCzPGTHNSmV
